### ISSUE TITLE
New Statement format

### ISSUE THREAD

**Issue by rehanfx** [penrosestudio/barclays-bank-pdf-to-csv#10]
It seems the barclays have changed their statement format from Jan 2015. Your tool does not work with this format. Any hope for supporting this:

![newstatement](https://cloud.githubusercontent.com/assets/7423989/6757428/d9c4110e-cf28-11e4-81ea-267034fe2119.png)

**Comment by shaggy8871** [comment]
The pull request https://github.com/penrosestudio/barclays-bank-pdf-to-csv/pull/13 solved it for me

**Comment by DisasterMan78** [comment]
Please check the notes on my pull request carefully, and manually check every entry - there may be other changes that I have not yet caught, and am unlikely to as I have data feeds directly to my accounting package now.

**Comment by jayfresh** [comment]
I've merged in #13, thanks!
