### ISSUE TITLE
doesn't include AFTS receipt

### ISSUE THREAD

**Issue by continuata** [penrosestudio/barclays-bank-pdf-to-csv#3]
This change seemed to fix most of my errors.

``` diff
diff --git a/statement-parser-lib.js b/statement-parser-lib.js
index e224296..2d86184 100644
--- a/statement-parser-lib.js
+++ b/statement-parser-lib.js
@@ -177,7 +177,8 @@
     "Debit card refund from",
     "Internet Banking transfer from",
     "Deposit", // NB: not sure this is a generic reference
-    "Refund from"
+    "Refund from",
+    "AFTS receipt from"
   ];
   var transactionsStart = 'Transactions in date order\\nDate\tDescription\tPaym
   /*
```

**Comment by jayfresh** [comment]
thanks! do you have any other errors that need addressing?

**Comment by continuata** [comment]
yeah I found a couple of other things that made it not work for me.
(change of year mainly)
I'm trying to process a few year's worth of statements in one go ... it's almost perfect.

I've forked the project and you can see my changes in there
https://github.com/continuata/barclays-bank-pdf-to-csv
