### ISSUE TITLE
issue working

### ISSUE THREAD

**Issue by nsiddique** [penrosestudio/barclays-bank-pdf-to-csv#5]
hi 

i keep getting the error 'could not find start of transactions in text, skipping page 1' on all the pdfs. I am using it with latest Barclays Business statements, has the format changed?

Thanks

**Comment by jayfresh** [comment]
It's possible that your statements have a different format to the ones I used. If you'd be comfortable sending me an example statement I can fix it for you - email is jonathan@penrosestudio.com

**Comment by xaurav** [comment]
Jay is right , although new statements has new format,  You can do 2 things
First in statement-parser-lib.js 

find

var transactionsStart = 'Transactions in date order\\nDate\tDescription\tPayments\tReceipts\tBalance';

change it to 

var transactionsStart = 'Date\tDescription\tMoney out £\tMoney in £\tBalance £';

or according to your table headings in statement

You can also add new values to arrays var payments = [ and var receipts = [

For example 	"AFTS payment re", in payments array.

Great Script by Jayfresh!! A++

**Comment by DisasterMan78** [comment]
It shouldn't actually be a problem IIRC - there are no transactions on the first page anymore.

Try my update - it works for me, and others have had success too.
https://github.com/penrosestudio/barclays-bank-pdf-to-csv/pull/13

**Comment by xaurav** [comment]
Hi thanks for quick reply, Your script fix works good . Comma instead of tab is great .

You can quick add following values to array payment in  statement-parser-lib.js
Which will be 
var payments = [
"AFTS payment re",
"CHAPS transfer to",
"Cheque issued",

Also onscreen csv output is still tab separated. It can be fixed too.

Great work !!

**Comment by DisasterMan78** [comment]
Excellent - new strings are vital.
I'll take a look this evening and issue a new pull request if you can test
it against your statements.

**Comment by xaurav** [comment]
Great, will be glad to test it .

Although I added new array var payments new values and it worked smooth at my end.

I have also changed the code to now..There is no need to run using node, Drag PDF to browser. It will automatically save CSV (Comma delimited ) with file name being dragged.

Works great at my end.

**Comment by DisasterMan78** [comment]
Sorry, I didn't get to it last night, and am now hectic for the rest of the
week. Will try to squeeze it in when I can...

**Comment by jayfresh** [comment]
I've added the extra payments into master in https://github.com/penrosestudio/barclays-bank-pdf-to-csv/commit/c35394f6c5eab58065b8ba10688e9d44c4b2039e. If you have some code that improves the in-browser version, please feel free to open a pull request
