### ISSUE TITLE
FreeAgent

### ISSUE THREAD

**Issue by davehodg** [penrosestudio/barclays-bank-pdf-to-csv#6]
My clone is sufficient to get data into FreeAgent.
The code is nasty, since I'm not a JavaScript guy (yet), the date stuff should have a hash for month, and/or got through a Date object, but hey.
Feel free to plunder (and make useful to people) or not!

**Comment by AlfieGreen** [comment]
Thanks Dave, that is exactly what I'm looking to pull it into! 

How do I go about setting this up?

**Comment by davehodg** [comment]
I've created a pull request, there should be instructions in there. Probably just a merge. But you'll definitely want to tidy up the JS!

**Comment by AlfieGreen** [comment]
I feel I might be doing something wrong, I just can't get it to pull the CSV file at the end for me.

So, I've cd'ed into: cd /Users/Alfie/Downloads/barclays-bank-pdf-to-csv-master/ - which works

Then, npm install

Which brings the below up:

Alfies-Macbook-Pro:barclays-bank-pdf-to-csv-master Alfie$ npm install
async@0.9.0 node_modules/async

Then I open the index file, and drag the PDF's in, but still no joy from there, it pulls in the pdf, but doesn't render the final file?

Any ideas?

**Comment by davehodg** [comment]
Sadly, no.
Are you using the original or my fork?

**Comment by AlfieGreen** [comment]
Trying with your one, but also tried the original! Is it working for you?

**Comment by davehodg** [comment]
I just used the command-line version. Worked quite well. Now in FreeAgent categorising everything!

**Comment by AlfieGreen** [comment]
Did you do anything different from the above to me? Sorry I've really got myself stuck with it haha!

**Comment by davehodg** [comment]
node statement-parser ../Statements/
No web necessary.

**Comment by AlfieGreen** [comment]
Sorry to be thick, I'm hoping you can help me get it running!

So, in terminal: git clone https://github.com/penrosestudio/barclays-bank-pdf-to-csv.git

Which installs it, then npm install, which just gives an error: 

npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/Alfie/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Alfie
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Alfie/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Alfie/npm-debug.log
npm ERR! not ok code 0

------------------

If I try: node statement-parser <Users/Alfie/Statements> I get the error:
-bash: syntax error near unexpected token `newline'

Did you do anything different? Am I missing a step? 

Thanks

**Comment by davehodg** [comment]
You don't appear to be in the barclays-bank-pdf-to-csv directory! you're in /Users/Alfie :)

Caught me first time too!

**Comment by jayfresh** [comment]
good catch! I was literally typing that out :)

**Comment by AlfieGreen** [comment]
Ah I see! So do i need to redirect this with cd?

**Comment by davehodg** [comment]
As I noted above:

node statement-parser ../Statements/

Where you have cd-ed to the barclays directory and ../Statements/ contains the PDFs...

**Comment by AlfieGreen** [comment]
I thought I had done this, apologies again for my lack of understanding of this!

cd /users/Alfie/barclays-bank-pdf-to-csv  

node statement-parser /Statements/

Which is where my folder is, however it still pulls the below error?


module.js:340
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Alfie/barclays-bank-pdf-to-csv/statement-parser.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
Alfies-MBP:barclays-bank-pdf-to-csv Alfie$

**Comment by davehodg** [comment]
That should be in ./node_modules/async/lib/async.js

**Comment by AlfieGreen** [comment]
Okay, I've resolved that...

However, now it is showing:

Alfies-MBP:barclays-bank-pdf-to-csv Alfie$ node statement-parser /Statements/

/Users/Alfie/barclays-bank-pdf-to-csv/statement-parser.js:12
    var pdfs = files.filter(function(fileName) {
                     ^
TypeError: Cannot call method 'filter' of undefined
    at csvPieces (/Users/Alfie/barclays-bank-pdf-to-csv/statement-parser.js:12:22)
    at Object.oncomplete (fs.js:108:15)
Alfies-MBP:barclays-bank-pdf-to-csv Alfie$

**Comment by davehodg** [comment]
There's something weird going on here. I worked for me straight away. 
I would recommend installing a fresh node (or npm update), cloning a new set of software and trying from scratch,

**Comment by AlfieGreen** [comment]
I did just try this, and the same error is coming up again and again... If not that error, it's telling me the folder doesn't contain any PDF's.

**Comment by davehodg** [comment]
What command are you using to invoke?

**Comment by AlfieGreen** [comment]
I'm slightly unsure as to what you mean?

The full reading is:

node statement-parser /Statements/

or 

node statement-parser /Users/Alfie/barclays-bank-pdf-to-csv/Statements/

**Comment by davehodg** [comment]
And you're positive you have *.pdf in there?

**Comment by AlfieGreen** [comment]
Inside /Statements/ is 5 .pdf files only, nothing else in the folder!

**Comment by davehodg** [comment]
And they're definitely Barclays business? I accidentally downloaded personal the first time...

**Comment by AlfieGreen** [comment]
All business yep!

**Comment by davehodg** [comment]
All i can say is works for me and delegate to the software owner :(

**Comment by AlfieGreen** [comment]
It's really annoying as I have around 1,500 lines in these statements I want to transfer into a CSV file/Freeagent... Just can't just past this step. Even in the web only verison nothing seems to come up! Thank you for your help though!

**Comment by davehodg** [comment]
If we assume a non-disclosure, do you want me to try one?

**Comment by AlfieGreen** [comment]
That would be over and above what I would expect, and would be greatly, greatly appreciated if you could so do!

**Comment by davehodg** [comment]
daveh@hodgkinson.org

**Comment by AlfieGreen** [comment]
Thanks Dave, I've popped you an email!

**Comment by AlfieGreen** [comment]
I think I've resolved it! It was because the extension was .PDF not .pdf!

**Comment by davehodg** [comment]
D'oh! OK, I'll delete your statement without opening

**Comment by AlfieGreen** [comment]
Thanks Dave! Hopefully it will help anyone else who stumbles across the same problem!

**Comment by davehodg** [comment]
File a bug :)

The author is awake :)

**Comment by jayfresh** [comment]
yup, will fix that

**Comment by jayfresh** [comment]
Closing as we have a separate issue (#9)
